name: Ignite San Francisco
markdown: redcarpet
pygments: true
relative_permalinks: false
nextEvent: "March 27, 2014"
twitter: ignitebayarea
facebookid: 320076143286
facebookurl: "https://www.facebook.com/ignitesanfrancisco"
url: "http://ignitesanfrancisco.com"
