name: Ignite San Francisco
markdown: kramdown
highlighter: rouge
relative_permalinks: false
next_event_date: "May 17th"
next_event_date_short: "May 17"
next_event_year: 2017
next_event_number: 13
twitter: theignitesf
facebookid: 320076143286
facebookurl: "https://www.facebook.com/ignitesanfrancisco"
url: "http://ignitesanfrancisco.com"
ticketurl: "https://www.eventbrite.com/e/ignite-sf-12-tickets-27896504195"
gems:
  - jekyll-redirect-from
